apparmor: false
arch:
- amd64
audio: true
description: Fully featured Visual Studio Code (vscode) experience integrated into
  the Home Assistant frontend.
devices:
- /dev/mem
docker_api: true
gpio: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_dbus: true
ingress: true
ingress_port: 9080
ingress_stream: true
init: false
map:
- addons:rw
- all_addon_configs:rw
- backup:rw
- homeassistant_config:rw
- media:rw
- share:rw
- ssl:rw
name: vscode
options:
  init_commands: []
  log_level: info
  packages: []
  ssh:
    allow_agent_forwarding: false
    allow_remote_port_forwarding: false
    allow_tcp_forwarding: false
    authorized_keys: []
    compatibility_mode: false
    password: ''
    sftp: false
    username: hassio
panel_icon: mdi:microsoft-visual-studio-code
ports:
  22/tcp: 22
ports_description:
  22/tcp: SSH server port (make empty to disable)
privileged:
- NET_ADMIN
- SYS_ADMIN
- SYS_RAWIO
- SYS_TIME
- SYS_NICE
schema:
  config_path: str?
  init_commands:
  - str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  packages:
  - str
  ssh:
    allow_agent_forwarding: bool
    allow_remote_port_forwarding: bool
    allow_tcp_forwarding: bool
    authorized_keys:
    - str
    compatibility_mode: bool
    password: password
    sftp: bool
    username: str
services:
- mysql:want
- mqtt:want
slug: vscode
startup: services
uart: true
url: https://github.com/finleyfamily/hass-addon-vscode
usb: true
version: 3fd4b8e
image: ghcr.io/finleyfamily/hass-addon-vscode/{arch}
